---
- name: Check all packages using Chocolatey
  hosts: all
  gather_facts: false
  tasks:

  - name: Check python version
    win_command: python --version
    register: check_python_version

  - name: Check nodejs version
    win_command: node --version
    register: check_node_version

  - debug:
      msg: Python Version is {{ check_python_version.stdout }}  and NodeJS version is 



- name: OPEN AN INCIDENT (SERVICENOW) IF PYTHON IS OUT OF DATE
      block:
        - name: CREATE AN INCIDENT
          snow_record:
            username: "admin"
            password: "GwWyg3KES7pz"
            instance: "dev67295"
            state: present
            table: incident
            data:
              short_description: "PYTHON is out of date on {{inventory_hostname}}"
              severity: 3
              priority: 2
              caller_id: "System Administrator"
              comments: "Python is out of date on {{inventory_hostname}}"
          register: snow_var
          delegate_to: localhost

        - name: VISUAL OUTPUT OF INCIDENT NUMBER
          debug:
            var: snow_var.record.number
       when: true
