---
- name: Check all packages using Chocolatey
  hosts: all
  gather_facts: false
  tasks:

  - name: Check python version
    win_command: python --version
    register: check_python_version

  - name: Check nodejs version
    win_command: node --version
    register: check_node_version

  - debug:
      msg: Python Version is {{ check_python_version.stdout }}  and NodeJS version is 
